### ISSUE TITLE
performance.py中 mp.Pool()那一部分函数在运行时会卡死...

### ISSUE THREAD

**Issue by zhanchao019** [ivanchiao/Recommend-System-Experiment#1]

**Comment by ivanchiao** [comment]
首先你的问题表述不清楚，我无法详细知道你的问题。其次，我的代码是在 1 块 RTX 2080Ti，4 核 CPU，内存无限制的云端运行的，如果卡死考虑是否是机器配置问题。
解决办法：
1. 降低 cores 的数量，code 中默认为4
2. performance.py 用来测试推荐性能指标，采用多进程方式。可以重写此处为单进程。
3. performance.py 且该部分耦合性较低，可以重写自己的版本。
4. python 解释器的版本为 3.6，考虑是否是版本问题。

**Comment by zhanchao019** [comment]
> 首先你的问题表述不清楚，我无法详细知道你的问题。其次，我的代码是在 1 块 RTX 2080Ti，4 核 CPU，内存无限制的云端运行的，如果卡死考虑是否是机器配置问题。
> 解决办法：
> 
> 1. 降低 cores 的数量，code 中默认为4
> 2. performance.py 用来测试推荐性能指标，采用多进程方式。可以重写此处为单进程。
> 3. performance.py 且该部分耦合性较低，可以重写自己的版本。
> 4. python 解释器的版本为 3.6，考虑是否是版本问题。

好滴，已经重写解决了。猜测可能因为租的服务器是16G内存内存不够导致的，谢谢
